### PR TITLE
Update l10n_ru.xml

### PR DESCRIPTION
**Pull request by vitalii2011**

### CODE REVIEW

**Comment by loki79uk** [comment]
You beat me to it!  There will be some new fields to add which is why I have not populated all of the language xml files yet.  It should be in the next update, and should not be too many new strings.

**Comment by loki79uk** [comment]
I hope that the latest file will be final now.  There are only three new ones to add for the MP permissions.

**Comment by vitalii2011** [comment]
No problem. I will do as much as I need, if circumstances permit. )
Translation of newlines:
```
		<text name="permission_lumberJack_superSpeed" text="Дровосек: Скорость"/>
		<text name="permission_lumberJack_superStrength" text="Дровосек: Сила"/>
		<text name="permission_lumberJack_chainsawSettings" text="Дровосек: Бензопила"/>
```

**Comment by loki79uk** [comment]
In case you are interested in using it, I have a new mod without any tranlsations: https://github.com/loki79uk/FS22_TipAnywhere/releases

**Comment by vitalii2011** [comment]
I'll take a look.

**Comment by loki79uk** [comment]
I added a new string - I used Google translate, but please check!

https://github.com/loki79uk/FS22_LumberJack/commit/a81a4d90859ba8d6971a195f17f4d83810ad6d76#diff-436780e7a7a59a095e425b8bc7e15dcbe33d46f13eb2b17eb73009b9a20e3017

**Comment by vitalii2011** [comment]
GT normally copes with fairly detailed/completed sentences, but with unsettled/new terms - - "as lucky". 
```
		<text name="setting_lumberJack_cutAnywhere" text="Пилить везде"/>
		<text name="toolTip_lumberJack_cutAnywhere" text="Игрок может использовать бензопилу в любом месте карты."/>
```

**Pull request merged**
